[package]
name = "audio_server"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]

[[bin]]
name = "audio_server"
path = "src/bin/main.rs"

[lib]
name = "audio_server"
path = "src/lib/lib.rs"

[dependencies]
conrod = { version = "0.58", features = ["winit", "glium"] }
conrod_derive = "0.1"
custom_derive = "0.1"
hound = "3.3"
newtype_derive = "0.1"
nannou = "0.2"
pitch_calc = "0.11"
rustfft = "2.0"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
time_calc = { version = "0.13", features = ["serde"] }
toml = "0.4"

[replace]
"nannou:0.2.0" = { path = "../../nannou" }
