[package]
name = "audio_server"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]

[[bin]]
name = "audio_server"
path = "src/bin/main.rs"

[lib]
name = "audio_server"
path = "src/lib/lib.rs"

[dependencies]
conrod = { version = "0.54", features = ["winit", "glium"] }
cpal = "0.4"
find_folder = "0.3"
image = "0.15"
rosc = "0.1"
sample = "0.6"
