[package]
name = "audio_server"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]

[[bin]]
name = "audio_server"
path = "src/bin/main.rs"

[lib]
name = "audio_server"
path = "src/lib/lib.rs"

[dependencies]
cgmath = { version = "0.15", features = ["serde"] }
conrod = { version = "0.55", features = ["winit", "glium"] }
cpal = "0.4"
custom_derive = "0.1"
find_folder = "0.3"
futures = "0.1"
hound = "3.1"
image = "0.15"
newtype_derive = "0.1"
rosc = "0.1"
sample = "0.7"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
time_calc = { version = "0.13", features = ["serde"] }
toml = "0.4"
