[package]
name = "audio_server"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]

[[bin]]
name = "audio_server"
path = "src/bin/main.rs"

[lib]
name = "audio_server"
path = "src/lib/lib.rs"

[dependencies]
conrod = { version = "0.56", features = ["winit", "glium"] }
conrod_derive = "0.1"
custom_derive = "0.1"
futures = "0.1"
hound = "3.1"
newtype_derive = "0.1"
nannou = { path = "../../nannou" }
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
time_calc = { version = "0.13", features = ["serde"] }
toml = "0.4"

[patch.crates-io]
cpal = { path = "../../cpal" }
