[package]
name = "audio_server"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]

[[bin]]
name = "audio_server"
path = "src/bin/main.rs"

[lib]
name = "audio_server"
path = "src/lib/lib.rs"

[dependencies]
#conrod = { version = "0.58", features = ["winit", "glium"] }
conrod = { git = "https://github.com/mitchmindtree/conrod", branch = "winit_glium_update", features = ["winit", "glium"] }
conrod_derive = "0.1"
custom_derive = "0.1"
fxhash = "0.2"
hound = "3.3"
mindtree_utils = "0.4"
newtype_derive = "0.1"
#nannou = "0.4"
nannou = { git = "https://github.com/mitchmindtree/nannou", branch = "glium_conrod_update" }
pitch_calc = "0.11"
rustfft = "2.0"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
slug = "0.1"
time_calc = { version = "0.13", features = ["serde"] }
toml = "0.4"
walkdir = "2"

[features]
test_with_stereo = [] # Compile with this feature to set the max i/o channels as `2`.
