[package]
name = "audio_server"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]

[[bin]]
name = "audio_server"
path = "src/bin/main.rs"

[lib]
name = "audio_server"
path = "src/lib/lib.rs"

[dependencies]
atomic = "0.3"
cgmath = "0.15"
conrod = { version = "0.55", features = ["winit", "glium"] }
cpal = "0.4"
custom_derive = "0.1"
find_folder = "0.3"
futures = "0.1"
image = "0.15"
newtype_derive = "0.1"
rosc = "0.1"
sample = "0.7"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
